services:
  frontend-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    network_mode: "host"
    volumes:
      
      - ./src:/app/src

      - ./public:/app/public
      
      - ./api:/app/api

    command: [sh, -c, 'npm run dev']
